version: '3.8'

services:
  django: 
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: django_web
    volumes:
      - ./backend/OstoriShop:/api 
    ports: 
      - '8000:8000'
    depends_on:
      - pgdb
    networks:  
      bridge_net:
        ipv4_address: 172.20.0.10 

  pgdb:
    image: postgres
    container_name: pgdb
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - backend/.env
    networks:
      - bridge_net

  redis:
    image: "redis:7.0.5-alpine"
    container_name: redis
    ports:
      - '6379:6379'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
    networks:
      - bridge_net

  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_app
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
    networks:
      bridge_net: 
        ipv4_address: 172.20.0.11  

networks:
  bridge_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16 
