version: '3.8'

services:
  django: 
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: django_web
    volumes:
      - ./backend/OstoriShop:/api 
    ports: 
      - '8000:8000'
    networks:  
      bridge_net:
        ipv4_address: 172.20.0.10 

  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_app
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
    networks:
      bridge_net: 
        ipv4_address: 172.20.0.11  

networks:
  bridge_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16 
