# Generated by Django 4.2.7 on 2024-05-16 11:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0006_remove_product_image_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('discount_amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Размер скидки')),
                ('promo_code', models.CharField(max_length=40, verbose_name='Промокод')),
                ('date_of_end', models.DateTimeField(verbose_name='Конец работы промокода')),
                ('product_categories', models.ManyToManyField(related_name='discount_categories', to='shop.category', verbose_name='Категории товаров')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
    ]
