# Generated by Django 4.2.7 on 2024-05-17 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_useddiscount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useddiscount',
            options={'verbose_name': 'Использованный промокод', 'verbose_name_plural': 'Использованные промокоды'},
        ),
        migrations.AlterField(
            model_name='useddiscount',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET, to='orders.discount', verbose_name='Промокод'),
        ),
    ]
