# Generated by Django 4.2.7 on 2024-05-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'В обработке'), ('delivery', 'Доставляется'), ('delivered', 'Доставлен')], default='processing', max_length=15, verbose_name='Статус заказа'),
        ),
    ]
