# Generated by Django 4.2.7 on 2024-05-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_discount_promo_code_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='promo_code',
            new_name='promocode',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'В обработке'), ('delivery', 'Доставляется'), ('delivered', 'Доставлен')], default='processing', max_length=15, verbose_name='Статус заказа'),
        ),
    ]
