# Generated by Django 4.2.7 on 2024-05-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_color_icon'),
        ('orders', '0010_rename_promo_code_discount_promocode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='product_categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='discount_categories', to='shop.category', verbose_name='Категории товаров'),
        ),
    ]
