# Generated by Django 4.2.7 on 2024-05-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_discount_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='idempotence_key',
            field=models.UUIDField(default=0, unique=True, verbose_name='Ключ идемпотентности'),
            preserve_default=False,
        ),
    ]
