# Generated by Django 4.2.7 on 2024-05-28 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='City',
            new_name='city',
        ),
    ]
