# Generated by Django 4.2.7 on 2024-05-28 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_rename_city_order_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('canceled', 'Отменен'), ('pending', 'Ожидает оплаты'), ('processing', 'В обработке'), ('delivery', 'Доставляется'), ('delivered', 'Доставлен')], default='pending', max_length=15, verbose_name='Статус заказа'),
        ),
    ]
