# Generated by Django 4.2.7 on 2024-05-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_code',
            field=models.UUIDField(default=0, verbose_name='Код платежа'),
            preserve_default=False,
        ),
    ]
