# Generated by Django 4.2.7 on 2024-05-28 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_order_payment_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_code',
            field=models.UUIDField(null=True, verbose_name='Код платежа'),
        ),
    ]
