# Generated by Django 4.2.7 on 2024-05-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=300, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='email адрес')),
                ('message', models.TextField(verbose_name='сообщение')),
                ('file', models.FileField(blank=True, null=True, upload_to='products/', verbose_name='файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='отправлен')),
            ],
            options={
                'verbose_name': 'обратная связь',
                'verbose_name_plural': 'обратная связь',
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='вопрос')),
                ('answer', models.TextField(verbose_name='ответ')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'db_table': 'help',
            },
        ),
    ]
