export const availableColors = [
  { color: 'Белый', label: 'Белый' },
  { color: 'Чёрный', label: 'Черный' },
  { color: 'Бежевый', label: 'Бежевый' },
  { color: 'Оливковый', label: 'Оливковый' },
  { color: 'Красный', label: 'Красный' },
  { color: 'Оранжевый', label: 'Оранжевый' },
  { color: 'Жёлтый', label: 'Желтый' },
  { color: 'Зелёный', label: 'Зеленый' },
  { color: 'Синий', label: 'Синий' },
  { color: 'Индиго', label: 'Индиго' },
  { color: 'Фиолетовый', label: 'Фиолетовый' },
  { color: 'Розовый', label: 'Розовый' },
  { color: 'Серый', label: 'Серый' },
  { color: 'Коричневый', label: 'Коричневый' },
];
