# Generated by Django 4.2.7 on 2024-02-17 15:25

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images/products', verbose_name='Иконка')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование')),
                ('image', models.ImageField(blank=True, upload_to='images/products')),
                ('article', models.CharField(blank=True, max_length=127, verbose_name='Артикул')),
                ('weight', models.FloatField(blank=True, default=0, verbose_name='Вес в кг.')),
                ('volume', models.FloatField(blank=True, default=0, verbose_name='Объем в см. куб.')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Цена')),
                ('quantity', models.IntegerField(blank=True, default=0, verbose_name='Доступно')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='products', related_query_name='categories', to='shop.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Комментарий')),
                ('is_moderated', models.BooleanField(default=False, verbose_name='Прошло модерацию')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shop.product', verbose_name='Товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв пользователя к товару',
                'verbose_name_plural': 'Отзывы пользователей к товарам',
            },
        ),
    ]
