# Generated by Django 4.2.7 on 2024-05-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, default='products/blank.png', null=True, upload_to='products/', verbose_name='Иконка'),
        ),
    ]
