# Generated by Django 4.2.7 on 2024-05-22 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_color_product_colors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Цвет', 'verbose_name_plural': 'Цвета'},
        ),
    ]
