# Generated by Django 4.2.7 on 2024-05-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_color_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Фотография товара', 'verbose_name_plural': 'Фотографии товаров'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'Размер', 'verbose_name_plural': 'Размеры'},
        ),
        migrations.AddField(
            model_name='color',
            name='icon',
            field=models.ImageField(blank=True, default='products/blank_color.png', null=True, upload_to='colors/', verbose_name='Иконка'),
        ),
    ]
