# Generated by Django 4.2.7 on 2024-05-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_productimage_options_alter_size_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='colors/', verbose_name='Иконка'),
        ),
    ]
