# Generated by Django 4.2.7 on 2024-05-22 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_color_options'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.color', verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.size', verbose_name='Цвет'),
        ),
    ]
