# Generated by Django 4.2.7 on 2024-05-22 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_color_options'),
        ('cart', '0002_cartproduct_color_cartproduct_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.color', verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.size', verbose_name='Цвет'),
        ),
    ]
