# Generated by Django 4.2.7 on 2024-05-29 06:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cartproduct_color_alter_cartproduct_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='count',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество товара'),
        ),
    ]
