# Generated by Django 4.2.7 on 2024-05-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='blank.jpg', null=True, upload_to='', verbose_name='Аватар'),
        ),
    ]
