# Generated by Django 4.2.7 on 2024-05-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='authentication/blank.png', null=True, upload_to='authentication/', verbose_name='Аватар'),
        ),
    ]
