import { Product } from '@/entities/model';
import { CardProps } from '@/entities/ui/card';

// Men
export const menJacketsProducts: CardProps[] = [
  {
    id: 'holly',
    title: 'Модель "Холли"',
    imageUrl: '/categories-grid/men/clothing/jackets/jacket8.jpg',
    alt: 'Jacket 2',
    price: 8999,
    rating: 4.5,
    reviewsCount: 4,
    cardPlates: [
      {
        variant: 'popular',
        label: 'Популярное',
      },
    ],
  },
  {
    id: 'avangard',
    title: 'Модель "Авангард"',
    imageUrl: '/categories-grid/men/clothing/jackets/jacket1.jpg',
    alt: 'Jacket 1',
    price: 5599,
    rating: 4.5,
    reviewsCount: 10,
  },
  {
    id: 'pulsar',
    title: 'Модель "Пульсар"',
    imageUrl: '/categories-grid/men/clothing/jackets/jacket2.jpg',
    alt: 'Jacket 2',
    price: 7999,
    rating: 3.5,
    reviewsCount: 5,
  },
  {
    id: 'stilleto',
    title: 'Модель "Стиллетто"',
    imageUrl: '/categories-grid/men/clothing/jackets/jacket3.jpg',
    alt: 'Jacket 2',
    price: 10999,
    rating: 4.0,
    reviewsCount: 5,
  },
  {
    id: 'forshaz',
    title: 'Модель "Форсаж"',
    imageUrl: '/categories-grid/men/clothing/jackets/jacket4.jpg',
    alt: 'Jacket 2',
    price: 150,
    rating: 4.0,
    reviewsCount: 5,
  },
  {
    id: 'aviator',
    title: 'Модель "Авиатор"',
    imageUrl: '/categories-grid/men/clothing/jackets/jacket5.jpg',
    alt: 'Jacket 2',
    price: 150,
    rating: 4.0,
    reviewsCount: 5,
  },
  {
    id: 'granit',
    title: 'Модель "Гранит"',
    imageUrl: '/categories-grid/men/clothing/jackets/jacket6.jpg',
    alt: 'Jacket 2',
    price: 150,
    rating: 4.0,
    reviewsCount: 5,
  },
  {
    id: 'marshal',
    title: 'Модель "Маршал"',
    imageUrl: '/categories-grid/men/clothing/jackets/jacket7.jpg',
    alt: 'Jacket 2',
    price: 150,
    rating: 4.0,
    reviewsCount: 5,
  },
];

export const menTShirtsProducts: CardProps[] = [
  {
    id: 'classic',
    title: 'Модель "Классик"',
    imageUrl: '/categories-grid/men/clothing/t-shirts/tshirt1.jpg',
    alt: 'T-Shirt 1',
    price: 1999,
    rating: 4.5,
    reviewsCount: 10,
    cardPlates: [
      {
        variant: 'popular',
        label: 'Популярное',
      },
    ],
  },
  {
    id: 'urban',
    title: 'Модель "Урбан"',
    imageUrl: '/categories-grid/men/clothing/t-shirts/tshirt2.jpg',
    alt: 'T-Shirt 2',
    price: 2499,
    rating: 4.0,
    reviewsCount: 8,
  },
  {
    id: 'sport',
    title: 'Модель "Спорт"',
    imageUrl: '/categories-grid/men/clothing/t-shirts/tshirt3.jpg',
    alt: 'T-Shirt 3',
    price: 1799,
    rating: 3.5,
    reviewsCount: 6,
  },
  {
    id: 'minimal',
    title: 'Модель "Минимал"',
    imageUrl: '/categories-grid/men/clothing/t-shirts/tshirt4.jpg',
    alt: 'T-Shirt 4',
    price: 2999,
    rating: 4.2,
    reviewsCount: 15,
  },
  {
    id: 'vintage',
    title: 'Модель "Винтаж"',
    imageUrl: '/categories-grid/men/clothing/t-shirts/tshirt5.jpg',
    alt: 'T-Shirt 5',
    price: 1899,
    rating: 4.8,
    reviewsCount: 12,
  },
];

export const menJeansProducts: CardProps[] = [
  {
    id: 'classicFit',
    title: 'Модель "Классический Фит"',
    imageUrl: '/categories-grid/men/clothing/jeans/jeans4.jpg',
    alt: 'Jeans 1',
    price: 3999,
    rating: 4.7,
    reviewsCount: 25,
    cardPlates: [
      {
        variant: 'popular',
        label: 'Популярное',
      },
    ],
  },
  {
    id: 'slimFit',
    title: 'Модель "Слим Фит"',
    imageUrl: '/categories-grid/men/clothing/jeans/jeans2.jpg',
    alt: 'Jeans 2',
    price: 4499,
    rating: 4.3,
    reviewsCount: 18,
  },
  {
    id: 'relaxedFit',
    title: 'Модель "Релакс Фит"',
    imageUrl: '/categories-grid/men/clothing/jeans/jeans6.jpg',
    alt: 'Jeans 3',
    price: 4299,
    rating: 4.5,
    reviewsCount: 20,
  },
  {
    id: 'taperedFit',
    title: 'Модель "Тейперед Фит"',
    imageUrl: '/categories-grid/men/clothing/jeans/jeans1.jpg',
    alt: 'Jeans 4',
    price: 3999,
    rating: 4.6,
    reviewsCount: 22,
  },
  {
    id: 'bootcut',
    title: 'Модель "Буткат"',
    imageUrl: '/categories-grid/men/clothing/jeans/jeans5.jpg',
    alt: 'Jeans 5',
    price: 4599,
    rating: 4.4,
    reviewsCount: 17,
  },
];

export const menShortsProducts: CardProps[] = [
  {
    id: 'cargo',
    title: 'Модель "Карго"',
    imageUrl: '/categories-grid/men/clothing/shorts/shorts1.jpg',
    alt: 'Shorts 1',
    price: 2999,
    rating: 4.3,
    reviewsCount: 14,
    cardPlates: [
      {
        variant: 'popular',
        label: 'Популярное',
      },
    ],
  },
  {
    id: 'denim',
    title: 'Модель "Деним"',
    imageUrl: '/categories-grid/men/clothing/shorts/shorts2.jpg',
    alt: 'Shorts 2',
    price: 3499,
    rating: 4.6,
    reviewsCount: 12,
  },
  {
    id: 'chino',
    title: 'Модель "Чино"',
    imageUrl: '/categories-grid/men/clothing/shorts/shorts3.jpg',
    alt: 'Shorts 3',
    price: 3199,
    rating: 4.1,
    reviewsCount: 9,
  },
  {
    id: 'sports',
    title: 'Модель "Спорт"',
    imageUrl: '/categories-grid/men/clothing/shorts/shorts4.jpg',
    alt: 'Shorts 4',
    price: 2799,
    rating: 4.4,
    reviewsCount: 13,
  },
  {
    id: 'swim',
    title: 'Модель "Свим"',
    imageUrl: '/categories-grid/men/clothing/shorts/shorts5.jpg',
    alt: 'Shorts 5',
    price: 2499,
    rating: 4.5,
    reviewsCount: 15,
  },
];

export const menSneakersProducts: CardProps[] = [
  {
    id: 'classicRun',
    title: 'Модель "Классик Ран"',
    imageUrl: '/categories-grid/men/shoes/sneakers/sneaker1.jpg',
    alt: 'Sneaker 1',
    price: 4999,
    rating: 4.7,
    reviewsCount: 30,
    cardPlates: [
      {
        variant: 'popular',
        label: 'Популярное',
      },
    ],
  },
  {
    id: 'urbanTrack',
    title: 'Модель "Урбан Трек"',
    imageUrl: '/categories-grid/men/shoes/sneakers/sneaker2.jpg',
    alt: 'Sneaker 2',
    price: 5499,
    rating: 4.5,
    reviewsCount: 25,
  },
  {
    id: 'sportX',
    title: 'Модель "Спорт X"',
    imageUrl: '/categories-grid/men/shoes/sneakers/sneaker3.jpg',
    alt: 'Sneaker 3',
    price: 3999,
    rating: 4.2,
    reviewsCount: 20,
  },
  {
    id: 'minimalRun',
    title: 'Модель "Минимал Ран"',
    imageUrl: '/categories-grid/men/shoes/sneakers/sneaker4.jpg',
    alt: 'Sneaker 4',
    price: 5999,
    rating: 4.8,
    reviewsCount: 35,
  },
  {
    id: 'retroWave',
    title: 'Модель "Ретро Вэйв"',
    imageUrl: '/categories-grid/men/shoes/sneakers/sneaker5.jpg',
    alt: 'Sneaker 5',
    price: 5299,
    rating: 4.6,
    reviewsCount: 28,
  },
];

export const menSandalsProducts: CardProps[] = [
  {
    id: 'beachWalk',
    title: 'Модель "Бич Вок"',
    imageUrl: '/categories-grid/men/shoes/sandals/sandal1.jpg',
    alt: 'Sandal 1',
    price: 2999,
    rating: 4.3,
    reviewsCount: 15,
    cardPlates: [
      {
        variant: 'popular',
        label: 'Популярное',
      },
    ],
  },
  {
    id: 'urbanStrap',
    title: 'Модель "Урбан Страп"',
    imageUrl: '/categories-grid/men/shoes/sandals/sandal2.jpg',
    alt: 'Sandal 2',
    price: 3499,
    rating: 4.5,
    reviewsCount: 18,
  },
  {
    id: 'comfortFlex',
    title: 'Модель "Комфорт Флекс"',
    imageUrl: '/categories-grid/men/shoes/sandals/sandal3.jpg',
    alt: 'Sandal 3',
    price: 2799,
    rating: 4.2,
    reviewsCount: 12,
  },
  {
    id: 'sportStrap',
    title: 'Модель "Спорт Страп"',
    imageUrl: '/categories-grid/men/shoes/sandals/sandal4.jpg',
    alt: 'Sandal 4',
    price: 3199,
    rating: 4.4,
    reviewsCount: 20,
  },
  {
    id: 'ecoWalk',
    title: 'Модель "Эко Вок"',
    imageUrl: '/categories-grid/men/shoes/sandals/sandal5.jpg',
    alt: 'Sandal 5',
    price: 2999,
    rating: 4.5,
    reviewsCount: 17,
  },
];

export const menBagsProducts: CardProps[] = [
  {
    id: 'urbanBackpack',
    title: 'Модель "Урбан Рюкзак"',
    imageUrl: '/categories-grid/men/accessories/bags/bag1.jpg',
    alt: 'Bag 1',
    price: 3999,
    rating: 4.7,
    reviewsCount: 20,
    cardPlates: [
      {
        variant: 'popular',
        label: 'Популярное',
      },
    ],
  },
  {
    id: 'leatherSatchel',
    title: 'Модель "Кожаный Сумка"',
    imageUrl: '/categories-grid/men/accessories/bags/bag2.jpg',
    alt: 'Bag 2',
    price: 5999,
    rating: 4.5,
    reviewsCount: 15,
  },
  {
    id: 'sportDuffel',
    title: 'Модель "Спорт Дюфель"',
    imageUrl: '/categories-grid/men/accessories/bags/bag3.jpg',
    alt: 'Bag 3',
    price: 4999,
    rating: 4.6,
    reviewsCount: 18,
  },
  {
    id: 'canvasMessenger',
    title: 'Модель "Канвас Мессенджер"',
    imageUrl: '/categories-grid/men/accessories/bags/bag4.jpg',
    alt: 'Bag 4',
    price: 3499,
    rating: 4.4,
    reviewsCount: 12,
  },
  {
    id: 'travelTote',
    title: 'Модель "Путешественный Тоте"',
    imageUrl: '/categories-grid/men/accessories/bags/bag5.jpg',
    alt: 'Bag 5',
    price: 4599,
    rating: 4.3,
    reviewsCount: 14,
  },
];

export const menBeltsProducts: CardProps[] = [
  {
    id: 'classicLeather',
    title: 'Модель "Классический Кожаный"',
    imageUrl: '/categories-grid/men/accessories/belts/belt1.jpg',
    alt: 'Belt 1',
    price: 1999,
    rating: 4.5,
    reviewsCount: 10,
    cardPlates: [
      {
        variant: 'popular',
        label: 'Популярное',
      },
    ],
  },
  {
    id: 'wovenStrap',
    title: 'Модель "Плетеный Ремень"',
    imageUrl: '/categories-grid/men/accessories/belts/belt2.jpg',
    alt: 'Belt 2',
    price: 2499,
    rating: 4.2,
    reviewsCount: 8,
  },
  {
    id: 'reversibleBelt',
    title: 'Модель "Двусторонний Ремень"',
    imageUrl: '/categories-grid/men/accessories/belts/belt3.jpg',
    alt: 'Belt 3',
    price: 2299,
    rating: 4.0,
    reviewsCount: 6,
  },
  {
    id: 'canvasBuckle',
    title: 'Модель "Канвас Бакл"',
    imageUrl: '/categories-grid/men/accessories/belts/belt4.jpg',
    alt: 'Belt 4',
    price: 1799,
    rating: 4.3,
    reviewsCount: 9,
  },
  {
    id: 'dressBelt',
    title: 'Модель "Офисный Ремень"',
    imageUrl: '/categories-grid/men/accessories/belts/belt5.jpg',
    alt: 'Belt 5',
    price: 2599,
    rating: 4.4,
    reviewsCount: 11,
  },
];

export const menHatsProducts: CardProps[] = [
  {
    id: 'baseballCap',
    title: 'Модель "Бейсболка"',
    imageUrl: '/categories-grid/men/accessories/hats/hat1.jpg',
    alt: 'Hat 1',
    price: 1499,
    rating: 4.5,
    reviewsCount: 10,
    cardPlates: [
      {
        variant: 'popular',
        label: 'Популярное',
      },
    ],
  },
  {
    id: 'fedora',
    title: 'Модель "Федора"',
    imageUrl: '/categories-grid/men/accessories/hats/hat2.jpg',
    alt: 'Hat 2',
    price: 2999,
    rating: 4.3,
    reviewsCount: 8,
  },
  {
    id: 'beanie',
    title: 'Модель "Шапка Бини"',
    imageUrl: '/categories-grid/men/accessories/hats/hat3.jpg',
    alt: 'Hat 3',
    price: 999,
    rating: 4.7,
    reviewsCount: 15,
  },
  {
    id: 'panamaHat',
    title: 'Модель "Панама"',
    imageUrl: '/categories-grid/men/accessories/hats/hat4.jpg',
    alt: 'Hat 4',
    price: 1999,
    rating: 4.4,
    reviewsCount: 12,
  },
  {
    id: 'flatCap',
    title: 'Модель "Флэт Кэп"',
    imageUrl: '/categories-grid/men/accessories/hats/hat5.jpg',
    alt: 'Hat 5',
    price: 1799,
    rating: 4.6,
    reviewsCount: 14,
  },
];

// Women
export const womenDressesProducts: CardProps[] = [
  {
    id: 'evening-dress',
    title: 'Вечернее платье',
    imageUrl: '/categories-grid/women/clothing/dresses/dress1.jpg',
    alt: 'Dress 1',
    price: 12999,
    rating: 4.9,
    reviewsCount: 45,
    cardPlates: [
      {
        variant: 'new',
        label: 'Новинка',
      },
    ],
  },
  {
    id: 'summer-dress',
    title: 'Летнее платье',
    imageUrl: '/categories-grid/women/clothing/dresses/dress2.jpg',
    alt: 'Dress 2',
    price: 8999,
    rating: 4.7,
    reviewsCount: 38,
  },
  {
    id: 'maxi-dress',
    title: 'Макси-платье',
    imageUrl: '/categories-grid/women/clothing/dresses/dress3.jpg',
    alt: 'Dress 3',
    price: 10999,
    rating: 4.8,
    reviewsCount: 42,
  },
  {
    id: 'cocktail-dress',
    title: 'Коктейльное платье',
    imageUrl: '/categories-grid/women/clothing/dresses/dress4.jpg',
    alt: 'Dress 4',
    price: 9499,
    rating: 4.6,
    reviewsCount: 36,
  },
  {
    id: 'casual-dress',
    title: 'Повседневное платье',
    imageUrl: '/categories-grid/women/clothing/dresses/dress5.jpg',
    alt: 'Dress 5',
    price: 7999,
    rating: 4.5,
    reviewsCount: 32,
  },
  {
    id: 'wedding-dress',
    title: 'Свадебное платье',
    imageUrl: '/categories-grid/women/clothing/dresses/dress6.jpg',
    alt: 'Dress 6',
    price: 25999,
    rating: 4.9,
    reviewsCount: 50,
  },
  {
    id: 'print-dress',
    title: 'Платье с принтом',
    imageUrl: '/categories-grid/women/clothing/dresses/dress7.jpg',
    alt: 'Dress 7',
    price: 6999,
    rating: 4.4,
    reviewsCount: 28,
  },
  {
    id: 'midi-dress',
    title: 'Миди-платье',
    imageUrl: '/categories-grid/women/clothing/dresses/dress8.jpg',
    alt: 'Dress 8',
    price: 8499,
    rating: 4.7,
    reviewsCount: 40,
  },
];

export const womenJacketsProducts: CardProps[] = [
  {
    id: 'luna',
    title: 'Модель "Луна"',
    imageUrl: '/categories-grid/women/clothing/jackets/jacket1.jpg',
    alt: 'Jacket 1',
    price: 8499,
    rating: 4.7,
    reviewsCount: 8,
    cardPlates: [
      {
        variant: 'new',
        label: 'Новинка',
      },
    ],
  },
  {
    id: 'venera',
    title: 'Модель "Венера"',
    imageUrl: '/categories-grid/women/clothing/jackets/jacket2.jpg',
    alt: 'Jacket 2',
    price: 7499,
    rating: 4.6,
    reviewsCount: 12,
  },
  {
    id: 'stellar',
    title: 'Модель "Стереллар"',
    imageUrl: '/categories-grid/women/clothing/jackets/jacket3.jpg',
    alt: 'Jacket 3',
    price: 9999,
    rating: 4.8,
    reviewsCount: 15,
  },
  {
    id: 'cosmo',
    title: 'Модель "Космо"',
    imageUrl: '/categories-grid/women/clothing/jackets/jacket4.jpg',
    alt: 'Jacket 4',
    price: 10999,
    rating: 4.9,
    reviewsCount: 9,
  },
  {
    id: 'eclipse',
    title: 'Модель "Эклипс"',
    imageUrl: '/categories-grid/women/clothing/jackets/jacket5.jpg',
    alt: 'Jacket 5',
    price: 12999,
    rating: 5.0,
    reviewsCount: 6,
  },
  {
    id: 'nova',
    title: 'Модель "Нова"',
    imageUrl: '/categories-grid/women/clothing/jackets/jacket6.jpg',
    alt: 'Jacket 6',
    price: 8999,
    rating: 4.7,
    reviewsCount: 11,
  },
  {
    id: 'aurora',
    title: 'Модель "Аврора"',
    imageUrl: '/categories-grid/women/clothing/jackets/jacket7.jpg',
    alt: 'Jacket 7',
    price: 9499,
    rating: 4.8,
    reviewsCount: 10,
  },
  {
    id: 'zenith',
    title: 'Модель "Зенит"',
    imageUrl: '/categories-grid/women/clothing/jackets/jacket8.jpg',
    alt: 'Jacket 8',
    price: 10499,
    rating: 4.9,
    reviewsCount: 7,
  },
];

export const womenTShirtsProducts: CardProps[] = [
  {
    id: 'sunny',
    title: 'Модель "Санни"',
    imageUrl: '/categories-grid/women/clothing/t-shirts/tshirt1.jpg',
    alt: 'T-Shirt 1',
    price: 1999,
    rating: 4.6,
    reviewsCount: 14,
    cardPlates: [
      {
        variant: 'popular',
        label: 'Популярное',
      },
    ],
  },
  {
    id: 'blossom',
    title: 'Модель "Блоссом"',
    imageUrl: '/categories-grid/women/clothing/t-shirts/tshirt2.jpg',
    alt: 'T-Shirt 2',
    price: 1599,
    rating: 4.5,
    reviewsCount: 18,
  },
  {
    id: 'flora',
    title: 'Модель "Флора"',
    imageUrl: '/categories-grid/women/clothing/t-shirts/tshirt3.jpg',
    alt: 'T-Shirt 3',
    price: 2499,
    rating: 4.8,
    reviewsCount: 22,
  },
  {
    id: 'aurora',
    title: 'Модель "Аврора"',
    imageUrl: '/categories-grid/women/clothing/t-shirts/tshirt4.jpg',
    alt: 'T-Shirt 4',
    price: 1799,
    rating: 4.7,
    reviewsCount: 10,
  },
  {
    id: 'luna',
    title: 'Модель "Луна"',
    imageUrl: '/categories-grid/women/clothing/t-shirts/tshirt5.jpg',
    alt: 'T-Shirt 5',
    price: 1999,
    rating: 4.6,
    reviewsCount: 8,
  },
  {
    id: 'starlight',
    title: 'Модель "Старлайт"',
    imageUrl: '/categories-grid/women/clothing/t-shirts/tshirt6.jpg',
    alt: 'T-Shirt 6',
    price: 2299,
    rating: 4.9,
    reviewsCount: 15,
  },
  {
    id: 'nova',
    title: 'Модель "Нова"',
    imageUrl: '/categories-grid/women/clothing/t-shirts/tshirt7.jpg',
    alt: 'T-Shirt 7',
    price: 1899,
    rating: 4.5,
    reviewsCount: 12,
  },
  {
    id: 'daisy',
    title: 'Модель "Дэйзи"',
    imageUrl: '/categories-grid/women/clothing/t-shirts/tshirt8.jpg',
    alt: 'T-Shirt 8',
    price: 1699,
    rating: 4.7,
    reviewsCount: 9,
  },
];

export const womenJeansProducts: CardProps[] = [
  {
    id: 'classic',
    title: 'Модель "Классик"',
    imageUrl: '/categories-grid/women/clothing/jeans/jeans1.jpg',
    alt: 'Jeans 1',
    price: 3499,
    rating: 4.8,
    reviewsCount: 20,
    cardPlates: [
      {
        variant: 'popular',
        label: 'Бестселлер',
      },
    ],
  },
  {
    id: 'slimfit',
    title: 'Модель "Слимфит"',
    imageUrl: '/categories-grid/women/clothing/jeans/jeans2.jpg',
    alt: 'Jeans 2',
    price: 2999,
    rating: 4.6,
    reviewsCount: 15,
  },
  {
    id: 'highwaist',
    title: 'Модель "Хайвейст"',
    imageUrl: '/categories-grid/women/clothing/jeans/jeans3.jpg',
    alt: 'Jeans 3',
    price: 3799,
    rating: 4.9,
    reviewsCount: 25,
  },
  {
    id: 'boyfriend',
    title: 'Модель "Бойфренд"',
    imageUrl: '/categories-grid/women/clothing/jeans/jeans4.jpg',
    alt: 'Jeans 4',
    price: 3199,
    rating: 4.7,
    reviewsCount: 18,
  },
  {
    id: 'skinny',
    title: 'Модель "Скинни"',
    imageUrl: '/categories-grid/women/clothing/jeans/jeans5.jpg',
    alt: 'Jeans 5',
    price: 2899,
    rating: 4.5,
    reviewsCount: 14,
  },
  {
    id: 'flare',
    title: 'Модель "Флар"',
    imageUrl: '/categories-grid/women/clothing/jeans/jeans6.jpg',
    alt: 'Jeans 6',
    price: 3599,
    rating: 4.8,
    reviewsCount: 19,
  },
  {
    id: 'distressed',
    title: 'Модель "Дистрессед"',
    imageUrl: '/categories-grid/women/clothing/jeans/jeans7.jpg',
    alt: 'Jeans 7',
    price: 3299,
    rating: 4.6,
    reviewsCount: 17,
  },
  {
    id: 'vintage',
    title: 'Модель "Винтаж"',
    imageUrl: '/categories-grid/women/clothing/jeans/jeans8.jpg',
    alt: 'Jeans 8',
    price: 2999,
    rating: 4.7,
    reviewsCount: 12,
  },
];

export const womenShortsProducts: CardProps[] = [
  {
    id: 'sunny',
    title: 'Модель "Санни"',
    imageUrl: '/categories-grid/women/clothing/shorts/shorts1.jpg',
    alt: 'Shorts 1',
    price: 1999,
    rating: 4.7,
    reviewsCount: 14,
    cardPlates: [
      {
        variant: 'popular',
        label: 'Популярное',
      },
    ],
  },
  {
    id: 'beach',
    title: 'Модель "Бич"',
    imageUrl: '/categories-grid/women/clothing/shorts/shorts2.jpg',
    alt: 'Shorts 2',
    price: 1599,
    rating: 4.5,
    reviewsCount: 12,
  },
  {
    id: 'city',
    title: 'Модель "Сити"',
    imageUrl: '/categories-grid/women/clothing/shorts/shorts3.jpg',
    alt: 'Shorts 3',
    price: 1799,
    rating: 4.6,
    reviewsCount: 18,
  },
  {
    id: 'casual',
    title: 'Модель "Кэжуал"',
    imageUrl: '/categories-grid/women/clothing/shorts/shorts4.jpg',
    alt: 'Shorts 4',
    price: 1499,
    rating: 4.4,
    reviewsCount: 10,
  },
  {
    id: 'sporty',
    title: 'Модель "Спорти"',
    imageUrl: '/categories-grid/women/clothing/shorts/shorts5.jpg',
    alt: 'Shorts 5',
    price: 1899,
    rating: 4.8,
    reviewsCount: 20,
  },
  {
    id: 'vintage',
    title: 'Модель "Винтаж"',
    imageUrl: '/categories-grid/women/clothing/shorts/shorts6.jpg',
    alt: 'Shorts 6',
    price: 1699,
    rating: 4.6,
    reviewsCount: 15,
  },
  {
    id: 'denim',
    title: 'Модель "Деним"',
    imageUrl: '/categories-grid/women/clothing/shorts/shorts7.jpg',
    alt: 'Shorts 7',
    price: 2099,
    rating: 4.7,
    reviewsCount: 17,
  },
  {
    id: 'holiday',
    title: 'Модель "Холидей"',
    imageUrl: '/categories-grid/women/clothing/shorts/shorts8.jpg',
    alt: 'Shorts 8',
    price: 1599,
    rating: 4.5,
    reviewsCount: 13,
  },
];

export const womenSneakersProducts: CardProps[] = [
  {
    id: 'flash',
    title: 'Модель "Флэш"',
    imageUrl: '/categories-grid/women/shoes/sneakers/sneakers1.jpg',
    alt: 'Sneakers 1',
    price: 4999,
    rating: 4.8,
    reviewsCount: 25,
    cardPlates: [
      {
        variant: 'popular',
        label: 'Популярное',
      },
    ],
  },
  {
    id: 'vortex',
    title: 'Модель "Вортекс"',
    imageUrl: '/categories-grid/women/shoes/sneakers/sneakers2.jpg',
    alt: 'Sneakers 2',
    price: 4799,
    rating: 4.6,
    reviewsCount: 18,
  },
  {
    id: 'comet',
    title: 'Модель "Комета"',
    imageUrl: '/categories-grid/women/shoes/sneakers/sneakers3.jpg',
    alt: 'Sneakers 3',
    price: 5299,
    rating: 4.7,
    reviewsCount: 22,
  },
  {
    id: 'nebula',
    title: 'Модель "Небула"',
    imageUrl: '/categories-grid/women/shoes/sneakers/sneakers4.jpg',
    alt: 'Sneakers 4',
    price: 4599,
    rating: 4.5,
    reviewsCount: 20,
  },
  {
    id: 'blaze',
    title: 'Модель "Блейз"',
    imageUrl: '/categories-grid/women/shoes/sneakers/sneakers5.jpg',
    alt: 'Sneakers 5',
    price: 4999,
    rating: 4.8,
    reviewsCount: 30,
  },
  {
    id: 'zenith',
    title: 'Модель "Зенит"',
    imageUrl: '/categories-grid/women/shoes/sneakers/sneakers6.jpg',
    alt: 'Sneakers 6',
    price: 4799,
    rating: 4.7,
    reviewsCount: 27,
  },
  {
    id: 'nova',
    title: 'Модель "Нова"',
    imageUrl: '/categories-grid/women/shoes/sneakers/sneakers7.jpg',
    alt: 'Sneakers 7',
    price: 5099,
    rating: 4.6,
    reviewsCount: 19,
  },
  {
    id: 'quantum',
    title: 'Модель "Квантум"',
    imageUrl: '/categories-grid/women/shoes/sneakers/sneakers8.jpg',
    alt: 'Sneakers 8',
    price: 4699,
    rating: 4.5,
    reviewsCount: 15,
  },
];

export const womenSandalsProducts: CardProps[] = [
  {
    id: 'oasis',
    title: 'Модель "Оазис"',
    imageUrl: '/categories-grid/women/shoes/sandals/sandals1.jpg',
    alt: 'Sandals 1',
    price: 2999,
    rating: 4.7,
    reviewsCount: 20,
    cardPlates: [
      {
        variant: 'new',
        label: 'Новое',
      },
    ],
  },
  {
    id: 'zen',
    title: 'Модель "Зен"',
    imageUrl: '/categories-grid/women/shoes/sandals/sandals2.jpg',
    alt: 'Sandals 2',
    price: 2799,
    rating: 4.6,
    reviewsCount: 15,
  },
  {
    id: 'breeze',
    title: 'Модель "Бриз"',
    imageUrl: '/categories-grid/women/shoes/sandals/sandals3.jpg',
    alt: 'Sandals 3',
    price: 3199,
    rating: 4.8,
    reviewsCount: 22,
  },
  {
    id: 'dune',
    title: 'Модель "Дюна"',
    imageUrl: '/categories-grid/women/shoes/sandals/sandals4.jpg',
    alt: 'Sandals 4',
    price: 2699,
    rating: 4.5,
    reviewsCount: 18,
  },
  {
    id: 'serene',
    title: 'Модель "Сирин"',
    imageUrl: '/categories-grid/women/shoes/sandals/sandals5.jpg',
    alt: 'Sandals 5',
    price: 2999,
    rating: 4.7,
    reviewsCount: 25,
  },
  {
    id: 'eclipse',
    title: 'Модель "Эклипс"',
    imageUrl: '/categories-grid/women/shoes/sandals/sandals6.jpg',
    alt: 'Sandals 6',
    price: 2899,
    rating: 4.6,
    reviewsCount: 20,
  },
  {
    id: 'ocean',
    title: 'Модель "Оушен"',
    imageUrl: '/categories-grid/women/shoes/sandals/sandals7.jpg',
    alt: 'Sandals 7',
    price: 3099,
    rating: 4.7,
    reviewsCount: 21,
  },
  {
    id: 'mirage',
    title: 'Модель "Мираж"',
    imageUrl: '/categories-grid/women/shoes/sandals/sandals8.jpg',
    alt: 'Sandals 8',
    price: 2799,
    rating: 4.5,
    reviewsCount: 17,
  },
];

export const womenBagsProducts: CardProps[] = [
  {
    id: 'classic-tote',
    title: 'Классическая сумка-тоут',
    imageUrl: '/categories-grid/women/accessories/bags/bag1.jpg',
    alt: 'Bag 1',
    price: 4999,
    rating: 4.8,
    reviewsCount: 30,
    cardPlates: [
      {
        variant: 'popular',
        label: 'Популярное',
      },
    ],
  },
  {
    id: 'city-backpack',
    title: 'Городской рюкзак',
    imageUrl: '/categories-grid/women/accessories/bags/bag2.jpg',
    alt: 'Bag 2',
    price: 3499,
    rating: 4.7,
    reviewsCount: 25,
  },
  {
    id: 'evening-clutch',
    title: 'Вечерний клатч',
    imageUrl: '/categories-grid/women/accessories/bags/bag3.jpg',
    alt: 'Bag 3',
    price: 2599,
    rating: 4.5,
    reviewsCount: 18,
  },
  {
    id: 'leather-shoulder',
    title: 'Кожаная сумка через плечо',
    imageUrl: '/categories-grid/women/accessories/bags/bag4.jpg',
    alt: 'Bag 4',
    price: 5999,
    rating: 4.9,
    reviewsCount: 32,
  },
  {
    id: 'minimalist-crossbody',
    title: 'Минималистичная сумка через плечо',
    imageUrl: '/categories-grid/women/accessories/bags/bag5.jpg',
    alt: 'Bag 5',
    price: 3799,
    rating: 4.6,
    reviewsCount: 20,
  },
  {
    id: 'weekend-duffle',
    title: 'Дорожная сумка',
    imageUrl: '/categories-grid/women/accessories/bags/bag6.jpg',
    alt: 'Bag 6',
    price: 4499,
    rating: 4.7,
    reviewsCount: 22,
  },
  {
    id: 'vintage-satchel',
    title: 'Винтажная сумка',
    imageUrl: '/categories-grid/women/accessories/bags/bag7.jpg',
    alt: 'Bag 7',
    price: 4299,
    rating: 4.8,
    reviewsCount: 28,
  },
  {
    id: 'canvas-shopper',
    title: 'Холщовая сумка-шоппер',
    imageUrl: '/categories-grid/women/accessories/bags/bag8.jpg',
    alt: 'Bag 8',
    price: 2999,
    rating: 4.5,
    reviewsCount: 15,
  },
];

export const womenBeltsProducts: CardProps[] = [
  {
    id: 'classic-leather',
    title: 'Классический кожаный ремень',
    imageUrl: '/categories-grid/women/accessories/belts/belt1.jpg',
    alt: 'Belt 1',
    price: 2999,
    rating: 4.7,
    reviewsCount: 25,
    cardPlates: [
      {
        variant: 'popular',
        label: 'Популярное',
      },
    ],
  },
  {
    id: 'stylish-buckle',
    title: 'Стильный ремень с пряжкой',
    imageUrl: '/categories-grid/women/accessories/belts/belt2.jpg',
    alt: 'Belt 2',
    price: 2499,
    rating: 4.6,
    reviewsCount: 20,
  },
  {
    id: 'slim-waist',
    title: 'Тонкий пояс',
    imageUrl: '/categories-grid/women/accessories/belts/belt3.jpg',
    alt: 'Belt 3',
    price: 1999,
    rating: 4.5,
    reviewsCount: 18,
  },
  {
    id: 'boho-belt',
    title: 'Бохо-ремень',
    imageUrl: '/categories-grid/women/accessories/belts/belt4.jpg',
    alt: 'Belt 4',
    price: 3499,
    rating: 4.8,
    reviewsCount: 30,
  },
  {
    id: 'wide-buckle',
    title: 'Ремень с широкой пряжкой',
    imageUrl: '/categories-grid/women/accessories/belts/belt5.jpg',
    alt: 'Belt 5',
    price: 2799,
    rating: 4.7,
    reviewsCount: 26,
  },
  {
    id: 'casual-belt',
    title: 'Повседневный ремень',
    imageUrl: '/categories-grid/women/accessories/belts/belt6.jpg',
    alt: 'Belt 6',
    price: 1799,
    rating: 4.4,
    reviewsCount: 15,
  },
  {
    id: 'ornate-belt',
    title: 'Изысканный ремень',
    imageUrl: '/categories-grid/women/accessories/belts/belt7.jpg',
    alt: 'Belt 7',
    price: 3999,
    rating: 4.9,
    reviewsCount: 32,
  },
  {
    id: 'fashion-belt',
    title: 'Модный ремень',
    imageUrl: '/categories-grid/women/accessories/belts/belt8.jpg',
    alt: 'Belt 8',
    price: 3299,
    rating: 4.6,
    reviewsCount: 22,
  },
];

export const womenHatsProducts: CardProps[] = [
  {
    id: 'wide-brim-hat',
    title: 'Широкополая шляпа',
    imageUrl: '/categories-grid/women/accessories/hats/hat1.jpg',
    alt: 'Hat 1',
    price: 3499,
    rating: 4.8,
    reviewsCount: 30,
    cardPlates: [
      {
        variant: 'popular',
        label: 'Популярное',
      },
    ],
  },
  {
    id: 'fedora-hat',
    title: 'Федора',
    imageUrl: '/categories-grid/women/accessories/hats/hat2.jpg',
    alt: 'Hat 2',
    price: 2999,
    rating: 4.6,
    reviewsCount: 25,
  },
  {
    id: 'beanie-hat',
    title: 'Шапка-бини',
    imageUrl: '/categories-grid/women/accessories/hats/hat3.jpg',
    alt: 'Hat 3',
    price: 1999,
    rating: 4.5,
    reviewsCount: 20,
  },
  {
    id: 'bucket-hat',
    title: 'Бакет',
    imageUrl: '/categories-grid/women/accessories/hats/hat4.jpg',
    alt: 'Hat 4',
    price: 2599,
    rating: 4.7,
    reviewsCount: 28,
  },
  {
    id: 'sun-hat',
    title: 'Солнечная шляпа',
    imageUrl: '/categories-grid/women/accessories/hats/hat5.jpg',
    alt: 'Hat 5',
    price: 2399,
    rating: 4.5,
    reviewsCount: 22,
  },
  {
    id: 'baseball-cap',
    title: 'Бейсболка',
    imageUrl: '/categories-grid/women/accessories/hats/hat6.jpg',
    alt: 'Hat 6',
    price: 1799,
    rating: 4.3,
    reviewsCount: 18,
  },
  {
    id: 'newsboy-cap',
    title: 'Гаврош',
    imageUrl: '/categories-grid/women/accessories/hats/hat7.jpg',
    alt: 'Hat 7',
    price: 2999,
    rating: 4.6,
    reviewsCount: 26,
  },
  {
    id: 'beret-cap',
    title: 'Берет',
    imageUrl: '/categories-grid/women/accessories/hats/hat8.jpg',
    alt: 'Hat 8',
    price: 2199,
    rating: 4.4,
    reviewsCount: 23,
  },
];

export const productDetails: Product[] = [
  {
    id: 'holly',
    name: 'Модель "Холли"',
    rating: 4.5,
    reviewsCount: 4,
    manufacturer: 'Some Brand',
    sizes: ['42', '44', '46', '48', '50', '52'],
    price: 8999,
    discountPrice: 8883,
    images: [
      '/categories-grid/men/clothing/jackets/jacket8.jpg',
      '/categories-grid/men/clothing/jackets/jacket8.jpg',
      '/categories-grid/men/clothing/jackets/jacket8.jpg',
      '/categories-grid/men/clothing/jackets/jacket8.jpg',
    ],
    material: 'Хлопок',
    color: 'Зелёный',
    description:
      'These are the classic Samba OG Shoes, perfect for casual wear.',
    reviews: [
      {
        user: 'Дмитрий Лукьянов',
        rating: 5,
        pros: 'Отличное качество',
        cons: 'Нет',
        comment: 'Супер!',
        date: '2024-05-01',
      },
      {
        user: 'Василий Чах',
        rating: 4,
        pros: 'Хороший дизайн',
        cons: 'Неудобные шнурки',
        comment: 'Супер!',
        date: '2024-04-21',
      },
      {
        user: 'Назар Петров',
        rating: 4.5,
        pros: 'Комфортные',
        cons: 'Цена',
        comment: 'Супер!',
        date: '2024-03-15',
      },
      {
        user: 'Николай Золотов',
        rating: 4,
        pros: 'Стильные',
        cons: 'Маркие',
        comment: 'Супер!',
        date: '2024-02-10',
      },
    ],
  },
];
