import { Product } from '@/entities/model';
import { CardProps } from '@/entities/ui/card';

export const menJacketsProducts: CardProps[] = [
  {
    id: 'holly',
    title: 'Модель "Холли"',
    imageUrl: '/categories-grid/men/clothing/jackets/jacket8.jpg',
    alt: 'Jacket 2',
    price: 8999,
    rating: 4.5,
    reviewsCount: 4,
    cardPlates: [
      {
        variant: 'popular',
        label: 'Популярное',
      },
    ],
  },
  {
    id: 'avangard',
    title: 'Модель "Авангард"',
    imageUrl: '/categories-grid/men/clothing/jackets/jacket1.jpg',
    alt: 'Jacket 1',
    price: 5599,
    rating: 4.5,
    reviewsCount: 10,
  },
  {
    id: 'pulsar',
    title: 'Модель "Пульсар"',
    imageUrl: '/categories-grid/men/clothing/jackets/jacket2.jpg',
    alt: 'Jacket 2',
    price: 7999,
    rating: 3.5,
    reviewsCount: 5,
  },
  {
    id: 'stilleto',
    title: 'Модель "Стиллетто"',
    imageUrl: '/categories-grid/men/clothing/jackets/jacket3.jpg',
    alt: 'Jacket 2',
    price: 10999,
    rating: 4.0,
    reviewsCount: 5,
  },
  {
    id: 'forshaz',
    title: 'Модель "Форсаж"',
    imageUrl: '/categories-grid/men/clothing/jackets/jacket4.jpg',
    alt: 'Jacket 2',
    price: 150,
    rating: 4.0,
    reviewsCount: 5,
  },
  {
    id: 'aviator',
    title: 'Модель "Авиатор"',
    imageUrl: '/categories-grid/men/clothing/jackets/jacket5.jpg',
    alt: 'Jacket 2',
    price: 150,
    rating: 4.0,
    reviewsCount: 5,
  },
  {
    id: 'granit',
    title: 'Модель "Гранит"',
    imageUrl: '/categories-grid/men/clothing/jackets/jacket6.jpg',
    alt: 'Jacket 2',
    price: 150,
    rating: 4.0,
    reviewsCount: 5,
  },
  {
    id: 'marshal',
    title: 'Модель "Маршал"',
    imageUrl: '/categories-grid/men/clothing/jackets/jacket7.jpg',
    alt: 'Jacket 2',
    price: 150,
    rating: 4.0,
    reviewsCount: 5,
  },
];

export const menTShirtsProducts: CardProps[] = [
  {
    id: 'classic',
    title: 'Модель "Классик"',
    imageUrl: '/categories-grid/men/clothing/t-shirts/tshirt1.jpg',
    alt: 'T-Shirt 1',
    price: 1999,
    rating: 4.5,
    reviewsCount: 10,
    cardPlates: [
      {
        variant: 'popular',
        label: 'Популярное',
      },
    ],
  },
  {
    id: 'urban',
    title: 'Модель "Урбан"',
    imageUrl: '/categories-grid/men/clothing/t-shirts/tshirt2.jpg',
    alt: 'T-Shirt 2',
    price: 2499,
    rating: 4.0,
    reviewsCount: 8,
  },
  {
    id: 'sport',
    title: 'Модель "Спорт"',
    imageUrl: '/categories-grid/men/clothing/t-shirts/tshirt3.jpg',
    alt: 'T-Shirt 3',
    price: 1799,
    rating: 3.5,
    reviewsCount: 6,
  },
  {
    id: 'minimal',
    title: 'Модель "Минимал"',
    imageUrl: '/categories-grid/men/clothing/t-shirts/tshirt4.jpg',
    alt: 'T-Shirt 4',
    price: 2999,
    rating: 4.2,
    reviewsCount: 15,
  },
  {
    id: 'vintage',
    title: 'Модель "Винтаж"',
    imageUrl: '/categories-grid/men/clothing/t-shirts/tshirt5.jpg',
    alt: 'T-Shirt 5',
    price: 1899,
    rating: 4.8,
    reviewsCount: 12,
  },
];

export const menJeansProducts: CardProps[] = [
  {
    id: 'classicFit',
    title: 'Модель "Классический Фит"',
    imageUrl: '/categories-grid/men/clothing/jeans/jeans4.jpg',
    alt: 'Jeans 1',
    price: 3999,
    rating: 4.7,
    reviewsCount: 25,
    cardPlates: [
      {
        variant: 'popular',
        label: 'Популярное',
      },
    ],
  },
  {
    id: 'slimFit',
    title: 'Модель "Слим Фит"',
    imageUrl: '/categories-grid/men/clothing/jeans/jeans2.jpg',
    alt: 'Jeans 2',
    price: 4499,
    rating: 4.3,
    reviewsCount: 18,
  },
  {
    id: 'relaxedFit',
    title: 'Модель "Релакс Фит"',
    imageUrl: '/categories-grid/men/clothing/jeans/jeans6.jpg',
    alt: 'Jeans 3',
    price: 4299,
    rating: 4.5,
    reviewsCount: 20,
  },
  {
    id: 'taperedFit',
    title: 'Модель "Тейперед Фит"',
    imageUrl: '/categories-grid/men/clothing/jeans/jeans1.jpg',
    alt: 'Jeans 4',
    price: 3999,
    rating: 4.6,
    reviewsCount: 22,
  },
  {
    id: 'bootcut',
    title: 'Модель "Буткат"',
    imageUrl: '/categories-grid/men/clothing/jeans/jeans5.jpg',
    alt: 'Jeans 5',
    price: 4599,
    rating: 4.4,
    reviewsCount: 17,
  },
];

export const menShortsProducts: CardProps[] = [
  {
    id: 'cargo',
    title: 'Модель "Карго"',
    imageUrl: '/categories-grid/men/clothing/shorts/shorts1.jpg',
    alt: 'Shorts 1',
    price: 2999,
    rating: 4.3,
    reviewsCount: 14,
    cardPlates: [
      {
        variant: 'popular',
        label: 'Популярное',
      },
    ],
  },
  {
    id: 'denim',
    title: 'Модель "Деним"',
    imageUrl: '/categories-grid/men/clothing/shorts/shorts2.jpg',
    alt: 'Shorts 2',
    price: 3499,
    rating: 4.6,
    reviewsCount: 12,
  },
  {
    id: 'chino',
    title: 'Модель "Чино"',
    imageUrl: '/categories-grid/men/clothing/shorts/shorts3.jpg',
    alt: 'Shorts 3',
    price: 3199,
    rating: 4.1,
    reviewsCount: 9,
  },
  {
    id: 'sports',
    title: 'Модель "Спорт"',
    imageUrl: '/categories-grid/men/clothing/shorts/shorts4.jpg',
    alt: 'Shorts 4',
    price: 2799,
    rating: 4.4,
    reviewsCount: 13,
  },
  {
    id: 'swim',
    title: 'Модель "Свим"',
    imageUrl: '/categories-grid/men/clothing/shorts/shorts5.jpg',
    alt: 'Shorts 5',
    price: 2499,
    rating: 4.5,
    reviewsCount: 15,
  },
];

export const menSneakersProducts: CardProps[] = [
  {
    id: 'classicRun',
    title: 'Модель "Классик Ран"',
    imageUrl: '/categories-grid/men/shoes/sneakers/sneaker1.jpg',
    alt: 'Sneaker 1',
    price: 4999,
    rating: 4.7,
    reviewsCount: 30,
    cardPlates: [
      {
        variant: 'popular',
        label: 'Популярное',
      },
    ],
  },
  {
    id: 'urbanTrack',
    title: 'Модель "Урбан Трек"',
    imageUrl: '/categories-grid/men/shoes/sneakers/sneaker2.jpg',
    alt: 'Sneaker 2',
    price: 5499,
    rating: 4.5,
    reviewsCount: 25,
  },
  {
    id: 'sportX',
    title: 'Модель "Спорт X"',
    imageUrl: '/categories-grid/men/shoes/sneakers/sneaker3.jpg',
    alt: 'Sneaker 3',
    price: 3999,
    rating: 4.2,
    reviewsCount: 20,
  },
  {
    id: 'minimalRun',
    title: 'Модель "Минимал Ран"',
    imageUrl: '/categories-grid/men/shoes/sneakers/sneaker4.jpg',
    alt: 'Sneaker 4',
    price: 5999,
    rating: 4.8,
    reviewsCount: 35,
  },
  {
    id: 'retroWave',
    title: 'Модель "Ретро Вэйв"',
    imageUrl: '/categories-grid/men/shoes/sneakers/sneaker5.jpg',
    alt: 'Sneaker 5',
    price: 5299,
    rating: 4.6,
    reviewsCount: 28,
  },
];

export const menSandalsProducts: CardProps[] = [
  {
    id: 'beachWalk',
    title: 'Модель "Бич Вок"',
    imageUrl: '/categories-grid/men/shoes/sandals/sandal1.jpg',
    alt: 'Sandal 1',
    price: 2999,
    rating: 4.3,
    reviewsCount: 15,
    cardPlates: [
      {
        variant: 'popular',
        label: 'Популярное',
      },
    ],
  },
  {
    id: 'urbanStrap',
    title: 'Модель "Урбан Страп"',
    imageUrl: '/categories-grid/men/shoes/sandals/sandal2.jpg',
    alt: 'Sandal 2',
    price: 3499,
    rating: 4.5,
    reviewsCount: 18,
  },
  {
    id: 'comfortFlex',
    title: 'Модель "Комфорт Флекс"',
    imageUrl: '/categories-grid/men/shoes/sandals/sandal3.jpg',
    alt: 'Sandal 3',
    price: 2799,
    rating: 4.2,
    reviewsCount: 12,
  },
  {
    id: 'sportStrap',
    title: 'Модель "Спорт Страп"',
    imageUrl: '/categories-grid/men/shoes/sandals/sandal4.jpg',
    alt: 'Sandal 4',
    price: 3199,
    rating: 4.4,
    reviewsCount: 20,
  },
  {
    id: 'ecoWalk',
    title: 'Модель "Эко Вок"',
    imageUrl: '/categories-grid/men/shoes/sandals/sandal5.jpg',
    alt: 'Sandal 5',
    price: 2999,
    rating: 4.5,
    reviewsCount: 17,
  },
];

export const menBagsProducts: CardProps[] = [
  {
    id: 'urbanBackpack',
    title: 'Модель "Урбан Рюкзак"',
    imageUrl: '/categories-grid/men/accessories/bags/bag1.jpg',
    alt: 'Bag 1',
    price: 3999,
    rating: 4.7,
    reviewsCount: 20,
    cardPlates: [
      {
        variant: 'popular',
        label: 'Популярное',
      },
    ],
  },
  {
    id: 'leatherSatchel',
    title: 'Модель "Кожаный Сумка"',
    imageUrl: '/categories-grid/men/accessories/bags/bag2.jpg',
    alt: 'Bag 2',
    price: 5999,
    rating: 4.5,
    reviewsCount: 15,
  },
  {
    id: 'sportDuffel',
    title: 'Модель "Спорт Дюфель"',
    imageUrl: '/categories-grid/men/accessories/bags/bag3.jpg',
    alt: 'Bag 3',
    price: 4999,
    rating: 4.6,
    reviewsCount: 18,
  },
  {
    id: 'canvasMessenger',
    title: 'Модель "Канвас Мессенджер"',
    imageUrl: '/categories-grid/men/accessories/bags/bag4.jpg',
    alt: 'Bag 4',
    price: 3499,
    rating: 4.4,
    reviewsCount: 12,
  },
  {
    id: 'travelTote',
    title: 'Модель "Путешественный Тоте"',
    imageUrl: '/categories-grid/men/accessories/bags/bag5.jpg',
    alt: 'Bag 5',
    price: 4599,
    rating: 4.3,
    reviewsCount: 14,
  },
];

export const menBeltsProducts: CardProps[] = [
  {
    id: 'classicLeather',
    title: 'Модель "Классический Кожаный"',
    imageUrl: '/categories-grid/men/accessories/belts/belt1.jpg',
    alt: 'Belt 1',
    price: 1999,
    rating: 4.5,
    reviewsCount: 10,
    cardPlates: [
      {
        variant: 'popular',
        label: 'Популярное',
      },
    ],
  },
  {
    id: 'wovenStrap',
    title: 'Модель "Плетеный Ремень"',
    imageUrl: '/categories-grid/men/accessories/belts/belt2.jpg',
    alt: 'Belt 2',
    price: 2499,
    rating: 4.2,
    reviewsCount: 8,
  },
  {
    id: 'reversibleBelt',
    title: 'Модель "Двусторонний Ремень"',
    imageUrl: '/categories-grid/men/accessories/belts/belt3.jpg',
    alt: 'Belt 3',
    price: 2299,
    rating: 4.0,
    reviewsCount: 6,
  },
  {
    id: 'canvasBuckle',
    title: 'Модель "Канвас Бакл"',
    imageUrl: '/categories-grid/men/accessories/belts/belt4.jpg',
    alt: 'Belt 4',
    price: 1799,
    rating: 4.3,
    reviewsCount: 9,
  },
  {
    id: 'dressBelt',
    title: 'Модель "Офисный Ремень"',
    imageUrl: '/categories-grid/men/accessories/belts/belt5.jpg',
    alt: 'Belt 5',
    price: 2599,
    rating: 4.4,
    reviewsCount: 11,
  },
];

export const menHatsProducts: CardProps[] = [
  {
    id: 'baseballCap',
    title: 'Модель "Бейсболка"',
    imageUrl: '/categories-grid/men/accessories/hats/hat1.jpg',
    alt: 'Hat 1',
    price: 1499,
    rating: 4.5,
    reviewsCount: 10,
    cardPlates: [
      {
        variant: 'popular',
        label: 'Популярное',
      },
    ],
  },
  {
    id: 'fedora',
    title: 'Модель "Федора"',
    imageUrl: '/categories-grid/men/accessories/hats/hat2.jpg',
    alt: 'Hat 2',
    price: 2999,
    rating: 4.3,
    reviewsCount: 8,
  },
  {
    id: 'beanie',
    title: 'Модель "Шапка Бини"',
    imageUrl: '/categories-grid/men/accessories/hats/hat3.jpg',
    alt: 'Hat 3',
    price: 999,
    rating: 4.7,
    reviewsCount: 15,
  },
  {
    id: 'panamaHat',
    title: 'Модель "Панама"',
    imageUrl: '/categories-grid/men/accessories/hats/hat4.jpg',
    alt: 'Hat 4',
    price: 1999,
    rating: 4.4,
    reviewsCount: 12,
  },
  {
    id: 'flatCap',
    title: 'Модель "Флэт Кэп"',
    imageUrl: '/categories-grid/men/accessories/hats/hat5.jpg',
    alt: 'Hat 5',
    price: 1799,
    rating: 4.6,
    reviewsCount: 14,
  },
];

export const productDetails: Product[] = [
  {
    id: 'holly',
    name: 'Модель "Холли"',
    rating: 4.5,
    reviewsCount: 4,
    manufacturer: 'Some Brand',
    sizes: ['42', '44', '46', '48', '50', '52'],
    price: 8999,
    discountPrice: 8883,
    images: [
      '/categories-grid/men/clothing/jackets/jacket8.jpg',
      '/categories-grid/men/clothing/jackets/jacket8.jpg',
      '/categories-grid/men/clothing/jackets/jacket8.jpg',
      '/categories-grid/men/clothing/jackets/jacket8.jpg',
    ],
    material: 'Хлопок',
    color: 'Зелёный',
    description:
      'These are the classic Samba OG Shoes, perfect for casual wear.',
    reviews: [
      {
        user: 'Дмитрий Лукьянов',
        rating: 5,
        pros: 'Отличное качество',
        cons: 'Нет',
        comment: 'Супер!',
        date: '2024-05-01',
      },
      {
        user: 'Василий Чах',
        rating: 4,
        pros: 'Хороший дизайн',
        cons: 'Неудобные шнурки',
        comment: 'Супер!',
        date: '2024-04-21',
      },
      {
        user: 'Назар Петров',
        rating: 4.5,
        pros: 'Комфортные',
        cons: 'Цена',
        comment: 'Супер!',
        date: '2024-03-15',
      },
      {
        user: 'Николай Золотов',
        rating: 4,
        pros: 'Стильные',
        cons: 'Маркие',
        comment: 'Супер!',
        date: '2024-02-10',
      },
    ],
  },
];
